#!/bin/sh

# Change to your own regext
PREFIX="????"
COMMIT_REGEX='(????-[0-9])'

INPUT_FILE=$1
COMMIT_MESSAGE=`head -n1 $INPUT_FILE`
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [[ $CURRENT_BRANCH =~ $PREFIX ]]; then
   if [[ ! "$COMMIT_MESSAGE" =~ "$CURRENT_BRANCH" ]]; then
      echo "Aborting commit. Your commit message is not the same as your branch"
      exit 1
   fi
fi

if [[ $CURRENT_BRANCH == "dev" || $CURRENT_BRANCH == "main" || $CURRENT_BRANCH != "master" ]]; then
   if [[ ! "$COMMIT_MESSAGE" =~ $COMMIT_REGEX ]]; then
      echo "Aborting commit. Your commit message does not start with JIRA Issue"
      exit 1
   fi
fi
